//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenneth.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBOUser
    {
        public long UIID { get; set; }
        public string UID { get; set; }
        public string PSW { get; set; }
        public string TICKET { get; set; }
        public string NAME { get; set; }
        public string IDNO { get; set; }
        public string EMAIL { get; set; }
        public string MOBILENO { get; set; }
        public int TYPE { get; set; }
        public string GENDER { get; set; }
        public string BIRTHDAY { get; set; }
        public string ADDR { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string SPELL { get; set; }
        public string PHOTO { get; set; }
        public string LastLoginTime { get; set; }
        public string BC { get; set; }
        public string IDTYPE { get; set; }
        public decimal Money { get; set; }
        public string TransPSW { get; set; }
        public string wx_openid { get; set; }
    }
}
