using System;

namespace Lenneth.Core.Framework.QR.Formater
{
    using Base;

    internal abstract class AbstractQrCode : IDisposable
    {
        protected QrCodeData QrCodeData { get; private set; }

        protected AbstractQrCode()
        {
        }

        protected AbstractQrCode(QrCodeData data) => QrCodeData = data;

        /// <summary>
        /// Set a QRCodeData object that will be used to generate QR code. Used in COM Objects connections
        /// </summary>
        /// <param name="data">Need a QRCodeData object generated by QRCodeGenerator.CreateQrCode()</param>
        public virtual void SetQrCodeData(QrCodeData data) => QrCodeData = data;

        public void Dispose() => QrCodeData = null;
    }
}